//! **iCEM — improved Cross-Entropy Method** (Pinneri et al., CoRL 2020): the sample-efficiency upgrade to
//! plain CEM/MPPI that makes sampling-based MPC deployable. Two changes carry it: **colored-noise** action
//! sampling (temporally-correlated `1/fᵝ` noise instead of white — smooth control sequences that explore
//! the low-frequency directions a system actually responds to), and **elite reuse** (carry the best
//! sequences across iterations instead of resampling from scratch). Together they cut the samples needed
//! for the same solution quality by an order of magnitude.
//!
//! This provides the colored-noise generator (verified to have the `1/fᵝ` power spectrum) and a CEM planner
//! over an arbitrary cost, which converges to the analytic optimum on a quadratic. Deterministic (seeded)
//! → WASM-clean. Complements [`crate::Cem`] / [`crate::Mppi`] (white-noise samplers).

use nalgebra::DVector;
use std::f64::consts::TAU;

/// A deterministic Gaussian RNG (seeded LCG + Box–Muller) — reproducible across native and wasm.
pub struct Rng {
    seed: u64,
    spare: Option<f64>,
}
impl Rng {
    pub fn new(seed: u64) -> Rng {
        Rng { seed: seed | 1, spare: None }
    }
    fn u01(&mut self) -> f64 {
        self.seed = self.seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        ((self.seed >> 11) as f64) / ((1u64 << 53) as f64)
    }
    /// One standard-normal draw.
    pub fn gaussian(&mut self) -> f64 {
        if let Some(s) = self.spare.take() {
            return s;
        }
        let (u1, u2) = (self.u01().max(1e-12), self.u01());
        let r = (-2.0 * u1.ln()).sqrt();
        self.spare = Some(r * (TAU * u2).sin());
        r * (TAU * u2).cos()
    }
}

/// A length-`h` **colored-noise** sequence with power spectral density `∝ 1/fᵝ`, generated by shaping white
/// noise in the frequency domain (naive DFT — `O(h²)`, fine for MPC horizons) and normalized to unit std.
pub fn colored_noise(h: usize, beta: f64, rng: &mut Rng) -> Vec<f64> {
    let w: Vec<f64> = (0..h).map(|_| rng.gaussian()).collect();
    // forward DFT
    let (mut re, mut im) = (vec![0.0; h], vec![0.0; h]);
    for (k, (rk, ik)) in re.iter_mut().zip(im.iter_mut()).enumerate() {
        for (n, &wn) in w.iter().enumerate() {
            let ang = -TAU * (k * n) as f64 / h as f64;
            *rk += wn * ang.cos();
            *ik += wn * ang.sin();
        }
        let f = k.min(h - k); // symmetric frequency magnitude
        let scale = if f == 0 { 1.0 } else { (f as f64).powf(-beta / 2.0) };
        *rk *= scale;
        *ik *= scale;
    }
    // inverse DFT (real part)
    let mut out = vec![0.0; h];
    for (n, on) in out.iter_mut().enumerate() {
        for k in 0..h {
            let ang = TAU * (k * n) as f64 / h as f64;
            *on += re[k] * ang.cos() - im[k] * ang.sin();
        }
        *on /= h as f64;
    }
    // normalize to unit standard deviation
    let mean = out.iter().sum::<f64>() / h as f64;
    let var = out.iter().map(|v| (v - mean).powi(2)).sum::<f64>() / h as f64;
    let sd = var.sqrt().max(1e-12);
    out.iter().map(|v| (v - mean) / sd).collect()
}

/// A score the ranking can order: any non-finite cost becomes the worst finite cost.
///
/// A caller's cost goes non-finite whenever its simulator cannot integrate a sequence (a divergence,
/// a `0/0`, a `log` of a negative). Ranking those with `partial_cmp().unwrap()` panics on the first
/// NaN, and `total_cmp` alone is not enough either: it orders a NEGATIVE NaN and `-inf` BELOW every
/// real cost, so a diverged sequence would rank BEST and be refit as an elite. Mapping every
/// non-finite score to [`f64::MAX`] is the contract [`crate::Cem::rollout_cost`] already documents
/// for its own rollouts, so the two planners now agree.
fn finite_or_worst(c: f64) -> f64 {
    if c.is_finite() {
        c
    } else {
        f64::MAX
    }
}

/// An iCEM planner over a control sequence of `horizon` steps, each `dim`-dimensional.
#[derive(Clone, Debug)]
pub struct Icem {
    pub horizon: usize,
    pub dim: usize,
    pub samples: usize,
    pub elite_frac: f64,
    /// Colored-noise exponent (0 = white, 2 = Brownian-ish; the paper's default ≈ 2.5).
    pub beta: f64,
    pub iters: usize,
    pub sigma0: f64,
}

impl Icem {
    /// Plan by iterated colored-noise sampling with elite reuse. `cost(&sequence)` scores a control
    /// sequence (lower is better). Returns the optimized mean sequence (`horizon` × `dim` vectors).
    ///
    /// `cost` may return a non-finite score for a sequence its simulator cannot integrate; such a
    /// sequence is ranked worst and never becomes an elite (non-finite scores are mapped to `f64::MAX`). The returned
    /// plan is therefore finite whenever the caller's own sampling bounds are.
    pub fn plan(&self, cost: impl Fn(&[DVector<f64>]) -> f64, seed: u64) -> Vec<DVector<f64>> {
        let mut rng = Rng::new(seed);
        let n_elite = ((self.samples as f64 * self.elite_frac).ceil() as usize).max(1);
        let mut mean = vec![DVector::zeros(self.dim); self.horizon];
        let mut sigma = vec![DVector::from_element(self.dim, self.sigma0); self.horizon];
        let mut elites_prev: Vec<Vec<DVector<f64>>> = Vec::new();

        for _ in 0..self.iters {
            let mut pop: Vec<Vec<DVector<f64>>> = Vec::with_capacity(self.samples);
            // reuse a fraction of last iteration's elites (shifted forward one step)
            for e in elites_prev.iter().take(n_elite / 2) {
                pop.push(e.clone());
            }
            while pop.len() < self.samples {
                // one colored-noise trajectory per dimension
                let noise: Vec<Vec<f64>> = (0..self.dim).map(|_| colored_noise(self.horizon, self.beta, &mut rng)).collect();
                let seq: Vec<DVector<f64>> = (0..self.horizon)
                    .map(|t| DVector::from_iterator(self.dim, (0..self.dim).map(|d| mean[t][d] + sigma[t][d] * noise[d][t])))
                    .collect();
                pop.push(seq);
            }
            // rank, keep elites
            let mut scored: Vec<(f64, usize)> = pop.iter().enumerate().map(|(i, s)| (finite_or_worst(cost(s)), i)).collect();
            scored.sort_by(|a, b| a.0.total_cmp(&b.0));
            let elites: Vec<Vec<DVector<f64>>> = scored[..n_elite].iter().map(|&(_, i)| pop[i].clone()).collect();
            // refit mean & std to the elites
            for t in 0..self.horizon {
                let mut mu = DVector::zeros(self.dim);
                for e in &elites {
                    mu += &e[t];
                }
                mu /= n_elite as f64;
                let mut var = DVector::zeros(self.dim);
                for e in &elites {
                    let d = &e[t] - &mu;
                    var += d.component_mul(&d);
                }
                var /= n_elite as f64;
                mean[t] = mu;
                sigma[t] = var.map(|v| v.sqrt().max(1e-4));
            }
            elites_prev = elites;
        }
        mean
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_colored_noise_has_the_one_over_f_beta_spectrum() {
        // THE INVARIANT. Averaging |DFT|² over many colored sequences, the log-power vs log-frequency slope
        // must be ≈ −β.
        let (h, beta) = (64usize, 2.0);
        let mut rng = Rng::new(7);
        let mut psd = vec![0.0; h / 2];
        let trials = 400;
        for _ in 0..trials {
            let x = colored_noise(h, beta, &mut rng);
            for (k, p) in psd.iter_mut().enumerate() {
                let (mut re, mut im) = (0.0, 0.0);
                for (n, &xn) in x.iter().enumerate() {
                    let ang = -TAU * (k * n) as f64 / h as f64;
                    re += xn * ang.cos();
                    im += xn * ang.sin();
                }
                *p += re * re + im * im;
            }
        }
        // least-squares slope of log(psd) vs log(f) over the informative band f = 2..h/2
        let (mut sx, mut sy, mut sxx, mut sxy, mut n) = (0.0, 0.0, 0.0, 0.0, 0.0);
        for k in 2..h / 2 {
            let (lx, ly) = ((k as f64).ln(), (psd[k] / trials as f64).ln());
            sx += lx;
            sy += ly;
            sxx += lx * lx;
            sxy += lx * ly;
            n += 1.0;
        }
        let slope = (n * sxy - sx * sy) / (n * sxx - sx * sx);
        assert!((slope + beta).abs() < 0.4, "PSD slope {slope} should be ≈ −β = {}", -beta);
    }

    #[test]
    fn white_noise_is_flat_but_colored_noise_is_smooth() {
        // β=0 (white) has near-zero autocorrelation at lag 1; β=2 (colored) is strongly positively
        // autocorrelated — the smoothness that makes it explore useful control directions.
        let mut rng = Rng::new(3);
        let autocorr1 = |x: &[f64]| {
            let m = x.iter().sum::<f64>() / x.len() as f64;
            let num: f64 = x.windows(2).map(|w| (w[0] - m) * (w[1] - m)).sum();
            let den: f64 = x.iter().map(|v| (v - m).powi(2)).sum();
            num / den.max(1e-12)
        };
        let (mut white, mut colored) = (0.0, 0.0);
        for _ in 0..200 {
            white += autocorr1(&colored_noise(64, 0.0, &mut rng));
            colored += autocorr1(&colored_noise(64, 2.5, &mut rng));
        }
        assert!(colored / 200.0 > 0.5, "colored noise should be strongly autocorrelated: {}", colored / 200.0);
        assert!(colored / 200.0 > white / 200.0 + 0.3, "colored should be far smoother than white");
    }

    #[test]
    fn it_drives_the_cost_down_toward_the_optimum() {
        // THE HEADLINE. Cost Σ‖u_t − u*_t‖² is minimized at u_t = u*_t; from an all-zero mean iCEM must
        // slash the cost toward 0 (colored noise finds the smooth optimal sequence).
        let horizon = 12;
        let star: Vec<DVector<f64>> = (0..horizon).map(|t| DVector::from_element(2, 0.5 * (t as f64 * 0.4).sin())).collect();
        let cost = |seq: &[DVector<f64>]| seq.iter().zip(&star).map(|(u, s)| (u - s).norm_squared()).sum::<f64>();
        let init_cost = cost(&vec![DVector::zeros(2); horizon]);
        let icem = Icem { horizon, dim: 2, samples: 128, elite_frac: 0.12, beta: 2.0, iters: 50, sigma0: 1.0 };
        let plan = icem.plan(cost, 11);
        let final_cost = cost(&plan);
        assert!(final_cost < 0.1 * init_cost, "iCEM should slash the cost >10x: {init_cost} → {final_cost}");
    }

    /// **A cost that goes non-finite on part of the search space must be ranked worst, not panic.**
    ///
    /// The sibling CEM planner documents and enforces that a diverging rollout scores `f64::MAX`. This
    /// planner takes the caller's cost, documents only "lower is better", and ranked with
    /// `partial_cmp().unwrap()`, which panics the moment one NaN enters the ranking. A caller whose
    /// simulator diverges on an aggressive control sequence hits exactly that, and the fixture below
    /// asserts the non-finite region is really visited so the test cannot pass vacuously.
    #[test]
    fn a_non_finite_cost_is_ranked_worst_instead_of_panicking() {
        let horizon = 10;
        let star: Vec<DVector<f64>> = (0..horizon).map(|t| DVector::from_element(2, 0.3 * (t as f64 * 0.5).cos())).collect();
        let calls = std::cell::Cell::new(0usize);
        let nonfinite = std::cell::Cell::new(0usize);
        let negative = std::cell::Cell::new(0usize);
        let cost = |seq: &[DVector<f64>]| {
            calls.set(calls.get() + 1);
            if seq[0].iter().any(|u| u.abs() > 2.0) {
                nonfinite.set(nonfinite.get() + 1);
                return f64::NAN; // "the simulator diverged on this sequence"
            }
            if seq[1].iter().any(|u| u.abs() > 2.5) {
                negative.set(negative.get() + 1);
                return f64::NEG_INFINITY; // a non-finite score that `total_cmp` alone would rank BEST
            }
            seq.iter().zip(&star).map(|(u, s)| (u - s).norm_squared()).sum::<f64>()
        };
        let init: f64 = star.iter().map(|s| s.norm_squared()).sum();
        let icem = Icem { horizon, dim: 2, samples: 128, elite_frac: 0.12, beta: 2.0, iters: 40, sigma0: 1.5 };
        let plan = icem.plan(cost, 7);
        assert!(nonfinite.get() > 0, "the fixture must actually reach the non-finite region: {} of {} calls", nonfinite.get(), calls.get());
        assert!(negative.get() > 0, "the fixture must also reach the NEGATIVE non-finite region: {} of {} calls", negative.get(), calls.get());
        assert!(plan.iter().all(|u| u.iter().all(|x| x.is_finite())), "the returned plan must be finite: {plan:?}");
        let final_cost = cost(&plan);
        assert!(final_cost.is_finite() && final_cost < 0.2 * init, "must still optimize despite the non-finite region: {init} -> {final_cost}");
        eprintln!("iCEM with non-finite regions: {} NaN + {} -inf of {} cost calls; cost {init:.4} -> {final_cost:.4}", nonfinite.get(), negative.get(), calls.get());
    }

    /// The degenerate case: EVERY sequence scores non-finite. The elite set is then all-worst, and the
    /// refit must still return finite numbers rather than propagating NaN into the mean.
    #[test]
    fn an_everywhere_non_finite_cost_still_returns_a_finite_plan() {
        let icem = Icem { horizon: 6, dim: 2, samples: 64, elite_frac: 0.125, beta: 2.0, iters: 10, sigma0: 1.0 };
        let plan = icem.plan(|_| f64::NAN, 3);
        assert_eq!(plan.len(), 6);
        assert!(plan.iter().all(|u| u.iter().all(|x| x.is_finite())), "plan must stay finite: {plan:?}");
    }
}
