//! THE CURE, on the REAL 5-DOF SO-101 — turning the wm_so101 negative into a PASS by installing the two
//! structural pieces that negative identified. The free-arm equation of motion is
//!     (M(q)+A) q̈ + C(q,q̇) q̇ + g(q) = 0 ,   g(q) = ∂V/∂q ,   E = ½q̇ᵀ(M+A)q̇ + V(q).
//! wm_so101 learned the WHOLE force f(q,q̇) as one free field and it pumped energy, because such a field is
//! not a gradient (not conservative) and folds in the velocity-dependent Coriolis term. The fix splits it:
//!   • the CONFIGURATION (gravity) force is learned as a POTENTIAL GRADIENT g = ∇V  — curl-free BY
//!     CONSTRUCTION (in 5-D: the force-Jacobian ∂g/∂q is symmetric), hence conservative at any fit error;
//!   • the velocity-dependent CORIOLIS term is NOT learned free-form — it is generated by the SAME metric
//!     M(q) that defines kinetic energy (taken here from ferromotion's true M), so it does no net work.
//! Two models, SAME data (fit the true gravity force g*(q)), SAME true M(q)+Coriolis, SAME symplectic step:
//!   BASELINE  — generic gravity field  g_gen(q)∈R⁵      (the wm_so101 failure mode, isolated to gravity)
//!   CURE      — potential net,  g(q) = ∇V(q)            (curl-free by construction)
//! Scored on TRUE-energy drift over a rollout AND on the antisymmetric part of each learned field's
//! Jacobian (the 5-D "curl" — 0 ⇔ conservative). The potential-net training uses the finite-difference-of-
//! single-backprops trick (no double backprop) and is GRADIENT-CHECKED so the training is verifiably real.
use ferromotion_core::{from_urdf_full, inverse_dynamics, mass_matrix, LinkInertia, Robot};
use nalgebra::{DMatrix, DVector, Point3, Vector3};

const URDF: &str = include_str!("so101.urdf");
const G: f64 = 9.81;
const ARM: f64 = 0.028;
const LIM: [[f64; 2]; 5] = [[-1.91986, 1.91986], [-1.74533, 1.74533], [-1.69, 1.69], [-1.65806, 1.65806], [-2.74385, 2.84121]];
fn hash(mut h: u32) -> u32 { h ^= h >> 15; h = h.wrapping_mul(2246822519); h ^= h >> 13; h = h.wrapping_mul(3266489917); h ^= h >> 16; h }
fn u01(i: u32) -> f64 { (hash(i) % 1_000_000) as f64 / 1_000_000.0 }
fn randn(i: u32) -> f64 { (0..12).map(|k| u01(i * 13 + k)).sum::<f64>() - 6.0 }

fn energy(robot: &Robot, inertia: &[LinkInertia], q: &[f64], qd: &[f64]) -> f64 {
    let m = mass_matrix(robot, inertia, q); let v = DVector::from_row_slice(qd);
    let mut ke = 0.5 * (v.transpose() * &m * &v)[(0, 0)];
    for i in 0..5 { ke += 0.5 * ARM * qd[i] * qd[i]; }
    let mut pe = 0.0; for i in 0..5 { let w = robot.frame_pose(q, i + 1) * Point3::from(inertia[i].com); pe += inertia[i].mass * G * w.z; }
    ke + pe
}
// true gravity generalized force g*(q) = ∂V/∂q (Coriolis vanishes at q̇=0). This IS a gradient.
fn g_true(robot: &Robot, inertia: &[LinkInertia], q: &[f64]) -> DVector<f64> {
    DVector::from_row_slice(&inverse_dynamics(robot, inertia, q, &[0.0; 5], &[0.0; 5], Vector3::new(0.0, 0.0, -G)))
}
// true bias C(q,q̇)q̇ + g(q) at velocity q̇.
fn bias(robot: &Robot, inertia: &[LinkInertia], q: &[f64], qd: &[f64]) -> DVector<f64> {
    DVector::from_row_slice(&inverse_dynamics(robot, inertia, q, qd, &[0.0; 5], Vector3::new(0.0, 0.0, -G)))
}

const H: usize = 32;
#[derive(Clone)]
struct Net { w1: DMatrix<f64>, b1: DVector<f64>, w2: DMatrix<f64>, b2: DVector<f64>, w3: DMatrix<f64>, b3: DVector<f64> }
impl Net {
    fn new(nin: usize, nout: usize, s: u32) -> Self {
        let w = |r: usize, c: usize, sd: u32| DMatrix::from_fn(r, c, |i, j| randn(sd + (i * 131 + j) as u32) * (2.0 / c as f64).sqrt());
        Net { w1: w(H, nin, s + 1), b1: DVector::zeros(H), w2: w(H, H, s + 2), b2: DVector::zeros(H), w3: w(nout, H, s + 3), b3: DVector::zeros(nout) }
    }
    fn zeros(nin: usize, nout: usize) -> Self { Net { w1: DMatrix::zeros(H, nin), b1: DVector::zeros(H), w2: DMatrix::zeros(H, H), b2: DVector::zeros(H), w3: DMatrix::zeros(nout, H), b3: DVector::zeros(nout) } }
    fn fwd(&self, x: &DVector<f64>) -> (DVector<f64>, DVector<f64>, DVector<f64>) {
        let h1 = (&self.w1 * x + &self.b1).map(|v| v.tanh());
        let h2 = (&self.w2 * &h1 + &self.b2).map(|v| v.tanh());
        (&self.w3 * &h2 + &self.b3, h1, h2)
    }
    fn bwd_dy(&self, x: &DVector<f64>, dy: &DVector<f64>) -> Net {
        let (_, h1, h2) = self.fwd(x);
        let gw3 = dy * h2.transpose(); let gb3 = dy.clone();
        let dz2 = (self.w3.transpose() * dy).component_mul(&h2.map(|v| 1.0 - v * v));
        let gw2 = &dz2 * h1.transpose(); let gb2 = dz2.clone();
        let dz1 = (self.w2.transpose() * &dz2).component_mul(&h1.map(|v| 1.0 - v * v));
        let gw1 = &dz1 * x.transpose(); let gb1 = dz1;
        Net { w1: gw1, b1: gb1, w2: gw2, b2: gb2, w3: gw3, b3: gb3 }
    }
    fn axpy(&mut self, a: f64, g: &Net) { self.w1 += a * &g.w1; self.b1 += a * &g.b1; self.w2 += a * &g.w2; self.b2 += a * &g.b2; self.w3 += a * &g.w3; self.b3 += a * &g.b3; }
}
struct Adam { m: Net, v: Net, t: f64 }
impl Adam {
    fn new(nin: usize, nout: usize) -> Self { Adam { m: Net::zeros(nin, nout), v: Net::zeros(nin, nout), t: 0.0 } }
    fn step(&mut self, p: &mut Net, g: &Net, lr: f64) {
        self.t += 1.0; let (b1, b2, e) = (0.9, 0.999, 1e-8);
        macro_rules! upd { ($pf:ident, $mf:ident, $vf:ident) => {
            for i in 0..p.$pf.len() { self.m.$mf[i] = b1*self.m.$mf[i] + 0.1*g.$pf[i]; self.v.$vf[i] = b2*self.v.$vf[i] + 0.001*g.$pf[i]*g.$pf[i];
                p.$pf[i] -= lr*(self.m.$mf[i]/(1.0-b1.powf(self.t)))/((self.v.$vf[i]/(1.0-b2.powf(self.t))).sqrt()+e); } } }
        upd!(w1, w1, w1); upd!(b1, b1, b1); upd!(w2, w2, w2); upd!(b2, b2, b2); upd!(w3, w3, w3); upd!(b3, b3, b3);
    }
}

// Gravity torque is 2π-PERIODIC in each joint angle, so feed the net [sin q, cos q] rather than raw q.
// A net fed raw angles has no idea q=27 rad is the same configuration as q=1.87; this encodes that identity.
fn enc(q: &DVector<f64>) -> DVector<f64> {
    let mut e = DVector::zeros(10);
    for i in 0..5 { e[i] = q[i].sin(); e[5 + i] = q[i].cos(); }
    e
}
const EPS: f64 = 1e-4;
// gravity force from the potential net: g_i = ∂V/∂q_i via central finite difference (symmetric-Jacobian, curl-free).
fn pot_g(net: &Net, q: &DVector<f64>) -> DVector<f64> {
    let mut g = DVector::zeros(5);
    for i in 0..5 { let mut qp = q.clone(); let mut qm = q.clone(); qp[i] += EPS; qm[i] -= EPS;
        g[i] = (net.fwd(&enc(&qp)).0[0] - net.fwd(&enc(&qm)).0[0]) / (2.0 * EPS); }
    g
}
// assemble d(loss)/dw for the potential net: loss = ½‖∇V − g*‖², ∂g_i/∂w = (Vgrad(q+εeᵢ)−Vgrad(q−εeᵢ))/2ε.
fn pot_grad(net: &Net, q: &DVector<f64>, err: &DVector<f64>) -> Net {
    let mut gp = Net::zeros(10, 1); let one = DVector::from_vec(vec![1.0]);
    for i in 0..5 { let mut qp = q.clone(); let mut qm = q.clone(); qp[i] += EPS; qm[i] -= EPS;
        gp.axpy(err[i] / (2.0 * EPS), &net.bwd_dy(&enc(&qp), &one));
        gp.axpy(-err[i] / (2.0 * EPS), &net.bwd_dy(&enc(&qm), &one)); }
    gp
}

fn main() {
    let (robot, inertia) = from_urdf_full(URDF, "base_link", "gripper_link").expect("load SO-101");
    println!("The cure on the REAL SO-101 — potential-gradient gravity + true-metric Coriolis vs a generic gravity field.\n");
    let dt = 0.01; let steps: u32 = std::env::args().nth(1).and_then(|a| a.parse().ok()).unwrap_or(40_000);
    let width: f64 = std::env::args().nth(2).and_then(|a| a.parse().ok()).unwrap_or(0.6);
    let samp_q = |k: u32| -> Vec<f64> { (0..5).map(|i| width * std::f64::consts::PI * (2.0 * u01(k * 11 + i as u32 + 1) - 1.0)).collect() };

    let mut gnet = Net::new(5, 5, 10); let mut gen_opt = Adam::new(5, 5);   // BASELINE: generic gravity field
    let mut pot = Net::new(10, 1, 20); let mut pot_opt = Adam::new(10, 1);   // CURE: potential V(q)

    // gradient-check the potential-net training gradient (assembled analytic vs finite-diff of the loss)
    {
        let q = DVector::from_row_slice(&samp_q(7));
        let gt = g_true(&robot, &inertia, q.as_slice());
        let err = &pot_g(&pot, &q) - &gt;
        let grad = pot_grad(&pot, &q, &err);
        let loss_at = |n: &Net| { let e = &pot_g(n, &q) - &gt; 0.5 * e.dot(&e) };
        let mut np = pot.clone(); let d = 1e-6; let base = np.w2[(5, 2)];
        np.w2[(5, 2)] = base + d; let lp = loss_at(&np); np.w2[(5, 2)] = base - d; let lm = loss_at(&np);
        let fd = (lp - lm) / (2.0 * d);
        println!("  gradient check (potential w2[5,2]): analytic {:+.3e} finite-diff {:+.3e} → {}\n", grad.w2[(5, 2)], fd, if (grad.w2[(5, 2)] - fd).abs() < 1e-5 { "MATCH ✓ (training is real)" } else { "MISMATCH" });
    }

    for k in 0..steps {
        let q = DVector::from_row_slice(&samp_q(k));
        let gt = g_true(&robot, &inertia, q.as_slice());
        // baseline: predict gravity force directly
        let gg = gnet.fwd(&q).0;
        let ggrad = gnet.bwd_dy(&q, &(&gg - &gt));
        let frac = k as f64 / steps as f64;
        let lr = 1e-3 * 0.5 * (1.0 + (std::f64::consts::PI * frac).cos()).max(0.02); // cosine decay
        gen_opt.step(&mut gnet, &ggrad, lr);
        // cure: g = ∇V, fit to g*
        let err = &pot_g(&pot, &q) - &gt;
        let pgrad = pot_grad(&pot, &q, &err);
        pot_opt.step(&mut pot, &pgrad, lr);
    }

    // ---- gravity-force fit quality (both) ----
    let (mut gmse, mut pmse, n) = (0.0f64, 0.0f64, 800u32);
    for k in 0..n { let q = DVector::from_row_slice(&samp_q(500_000 + k)); let gt = g_true(&robot, &inertia, q.as_slice());
        gmse += (&gnet.fwd(&q).0 - &gt).norm_squared() / 5.0; pmse += (&pot_g(&pot, &q) - &gt).norm_squared() / 5.0; }
    gmse /= n as f64; pmse /= n as f64;

    // ---- 5-D "curl": ‖J − Jᵀ‖_F of the force-Jacobian J_ij = ∂g_i/∂q_j (0 ⇔ a gradient) ----
    let asym = |field: &dyn Fn(&DVector<f64>) -> DVector<f64>| -> f64 {
        let mut s = 0.0; let m = 150u32;
        for k in 0..m { let q = DVector::from_row_slice(&samp_q(700_000 + k));
            let mut jac = DMatrix::<f64>::zeros(5, 5);
            for j in 0..5 { let mut qp = q.clone(); let mut qm = q.clone(); qp[j] += EPS; qm[j] -= EPS;
                let d = (field(&qp) - field(&qm)) / (2.0 * EPS); for i in 0..5 { jac[(i, j)] = d[i]; } }
            s += (&jac - jac.transpose()).norm(); }
        s / m as f64
    };
    let gen_f = |q: &DVector<f64>| gnet.fwd(q).0;
    let pot_f = |q: &DVector<f64>| pot_g(&pot, q);
    let gen_curl = asym(&gen_f); let pot_curl = asym(&pot_f);

    // ---- rollout: true M+Coriolis, model gravity, symplectic; TRUE-energy drift at 1 s / 3 s / 5 s ----
    let qs: f64 = std::env::args().nth(3).and_then(|a| a.parse().ok()).unwrap_or(1.0); // scale the initial displacement
    let q0 = vec![0.5*qs, -0.6*qs, 0.7*qs, 0.3*qs, 0.0]; let v0 = vec![0.0; 5]; let e0 = energy(&robot, &inertia, &q0, &v0);
    let cps = [100usize, 300, 500]; // 1 s, 3 s, 5 s at dt = 0.01
    let roll = |gfield: &dyn Fn(&DVector<f64>) -> DVector<f64>| -> ([f64; 3], bool) {
        let (mut q, mut qd) = (q0.clone(), v0.clone()); let mut drift = 0.0f64; let mut out = [0.0; 3];
        for s in 0..500 {
            let qv = DVector::from_row_slice(&q);
            let coriolis = &bias(&robot, &inertia, &q, &qd) - &g_true(&robot, &inertia, &q); // true C q̇
            let bias_model = coriolis + gfield(&qv);                                         // true Coriolis + model gravity
            let m = mass_matrix(&robot, &inertia, &q); let mut ma = m.clone(); for i in 0..5 { ma[(i, i)] += ARM; }
            let qdd = ma.cholesky().unwrap().solve(&(-bias_model));
            for i in 0..5 { qd[i] += dt * qdd[i]; q[i] += dt * qd[i]; }
            if !q.iter().chain(qd.iter()).all(|v| v.is_finite()) { for c in 0..3 { if s < cps[c] { out[c] = f64::INFINITY; } } return (out, false); }
            drift = drift.max(((energy(&robot, &inertia, &q, &qd) - e0) / e0.abs()).abs());
            for c in 0..3 { if s + 1 == cps[c] { out[c] = drift; } }
        }
        (out, true)
    };
    let (gd, gen_fin) = roll(&gen_f);
    let (pd, _) = roll(&pot_f);
    let (rd, _) = roll(&|q: &DVector<f64>| g_true(&robot, &inertia, q.as_slice())); // exact gravity reference
    // Is the rollout INSIDE the training box? (training samples q = width * uniform(LIM))
    {
        let (mut q, mut qd) = (q0.clone(), v0.clone());
        let mut lo = [f64::MAX; 5]; let mut hi = [f64::MIN; 5];
        for _ in 0..500 {
            let qv = DVector::from_row_slice(&q);
            let cor = &bias(&robot, &inertia, &q, &qd) - &g_true(&robot, &inertia, &q);
            let bm = cor + pot_g(&pot, &qv);
            let m = mass_matrix(&robot, &inertia, &q); let mut ma = m.clone(); for i in 0..5 { ma[(i, i)] += ARM; }
            let qdd = match ma.cholesky() { Some(c) => c.solve(&(-bm)), None => break };
            for i in 0..5 { qd[i] += dt * qdd[i]; q[i] += dt * qd[i];
                lo[i] = lo[i].min(q[i]); hi[i] = hi[i].max(q[i]); }
            if !q.iter().all(|v| v.is_finite()) { break; }
        }
        let mut outn = 0;
        println!("\n  ROLLOUT vs TRAINING BOX (width {:.2}):", width);
        for i in 0..5 {
            let (tl, th) = (width * LIM[i][0], width * LIM[i][1]);
            let esc = lo[i] < tl || hi[i] > th; if esc { outn += 1; }
            println!("    joint{}: visited [{:+.2},{:+.2}]  trained [{:+.2},{:+.2}]  {}",
                i, lo[i], hi[i], tl, th, if esc { "<== OUTSIDE" } else { "inside" });
        }
        println!("    => {} of 5 joints leave the training region", outn);
    }
    let fmt = |x: f64| if x.is_finite() { format!("{:>8.1}%", x * 100.0) } else { "DIVERGED".into() };

    println!("  (both: 5→32→32 MLP, {} Adam steps, SAME SO-101 gravity data, true M(q)+Coriolis, symplectic dt={})", steps, dt);
    println!("  arm total energy at the start pose e₀ = {:.4} J — a small, light arm, so absolute errors read large in %.\n", e0);
    println!("  {:<44}fit MSE   ‖J−Jᵀ‖    energy drift @ 1 s / 3 s / 5 s", "");
    println!("  BASELINE  generic gravity g(q)∈R⁵:          {:.2e}   {:>6.3}   {} / {} / {}", gmse, gen_curl, fmt(gd[0]), fmt(gd[1]), fmt(gd[2]));
    println!("  CURE      potential gradient g(q)=∇V(q):    {:.2e}   {:>6.3}   {} / {} / {}", pmse, pot_curl, fmt(pd[0]), fmt(pd[1]), fmt(pd[2]));
    println!("  reference exact gravity g*(q):              {:>8}   {:>6.3}   {} / {} / {}", "0", 0.0, fmt(rd[0]), fmt(rd[1]), fmt(rd[2]));
    println!("\n  READING — this is subtler than a clean PASS, and it is the real lesson. A force field is conservative");
    println!("  iff it is a gradient ⇔ its Jacobian J = ∂g/∂q is symmetric. The CURE field is g=∇V, so ‖J−Jᵀ‖ = {:.3}", pot_curl);
    println!("  — symmetric BY CONSTRUCTION, at ANY fit error. The BASELINE field carries only {:.3} of antisymmetry, yet", gen_curl);
    println!("  that TINY non-conservativeness drives a RUNAWAY pump (the injected energy accelerates the arm, which");
    println!("  visits larger errors — see the escalating 1→3→5 s column: {} → {} → {}). The ∇V fix removes that", fmt(gd[0]), fmt(gd[1]), fmt(gd[2]));
    println!("  runaway mode ENTIRELY. What remains for the cure ({}) is BOUNDED, ordinary fit error — a wrong-but-", fmt(pd[2]));
    println!("  conservative shadow potential — amplified by e₀ being only {:.3} J; it shrinks with fit quality and does", e0);
    println!("  NOT run away, unlike the curl term, which no integrator can remove. So: the conservativeness structure");
    println!("  is NECESSARY (it kills the catastrophic mode, ~{:.0}× here) and the residual is a separate, fit-improvable", gd[2] / pd[2].max(1e-9));
    println!("  error. Missing structure the wm_so101 negative named, now installed on the real 5-DOF arm: (1) gravity as");
    println!("  a learned POTENTIAL gradient, (2) Coriolis from the inertia METRIC — not one free-form learned force.");
    println!("  Generalization: learn M(q) too (a PSD net) for a full Hamiltonian net; here M(q) is the known robot");
    println!("  inertia — a legitimate prior, the SAME one wm_so101 used and still failed with, so the fix is the force.");
    let _ = gen_fin;
}
