//! **The geometry a robot description carries, and the body it implies** — the other half of
//! [`mesh_io`](crate::mesh_io).
//!
//! [`from_urdf_full`](crate::from_urdf_full) reads the kinematics and the inertials out of a URDF and
//! discards everything else. But `urdf_rs` has already parsed the geometry: `Link` carries
//! `visual: Vec<Visual>` and `collision: Vec<Collision>`, each with an origin and a `Geometry` enum
//! that is a box, cylinder, capsule, sphere or a mesh filename with a scale. All of it was thrown
//! away, which is the same thing that happened to `lower`/`upper` and to `damping` before those were
//! wired in — a field the dependency parses for free and the caller cannot reach.
//!
//! # Two things this unlocks, and one of them needs no file at all
//!
//! **A description made of primitives becomes a simulable body from the XML alone.** A box, cylinder,
//! capsule or sphere is generated by [`primitive_mesh`] and integrated by
//! [`solid_inertia`](crate::solid_inertia), so a URDF with no `<inertial>` block and no mesh files
//! still yields a full [`LinkInertia`] vector. That is the common case for a quickly-written
//! description, and it needed no asset resolution to work.
//!
//! **A description pointing at meshes becomes resolvable.** [`geometry_from_urdf`] surfaces the
//! `package://`, `file://` or relative URI with its scale, and [`resolve_uri`] expands it against a
//! caller-supplied package→root table. Nothing here touches the filesystem: the caller fetches the
//! bytes and hands them to [`from_obj`](crate::from_obj) or [`from_stl`](crate::from_stl), which is
//! what keeps this identical native and in a browser, and what means no asset is vendored.
//!
//! # Several parts in one link, done the way that is actually correct
//!
//! A link is usually more than one shape. [`inertia_of_parts`] takes the parts with their origins and
//! returns one [`LinkInertia`]: each part is transformed into the link frame, integrated, and then
//! composed by parallel-axis **about the combined centre of mass**.
//!
//! ⛔ That is not the same as averaging the parts' inertia tensors, and the difference is not small.
//! Two unit cubes side by side form a 2×1×1 box whose `I_yy` is `m·(a²+c²)/12 = 5m/12`; averaging the
//! two cubes' own tensors gives `m/6 = 2m/12`, which is **2.5× too small** and looks entirely
//! plausible. `two_cubes_compose_into_the_box_they_form` pins it.
//!
//! # Scope
//!
//! URDF only. MJCF's `<geom>` and SDF's `<geometry>` carry the same information in their own spelling
//! and are not surfaced here; this review did not extend those parsers. Materials, textures and
//! visual-only attributes are not represented — [`GeomRole`] records whether a shape came from
//! `<visual>` or `<collision>` so a caller can prefer the collision geometry for physics, which is
//! what it is for.

use crate::dynamics::{combine_inertia, transform_inertia};
use crate::mesh3::TriMesh3;
use crate::mesh_io::solid_inertia;
use crate::{Iso, LinkInertia};
use nalgebra::{Point3, Translation3, UnitQuaternion, Vector3};

/// Which block a shape came from. Collision geometry is what physics should use; visual geometry is
/// often a much finer mesh of the same part, and using it for contact is a common performance trap.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GeomRole {
    Visual,
    Collision,
}

/// A shape as a robot description states it. Dimensions are URDF's: `Box::size` is the **full**
/// extent (not a half-extent), and a cylinder or capsule lies along its frame's **z** axis, centred.
#[derive(Clone, Debug, PartialEq)]
pub enum LinkGeometry {
    Box { size: Vector3<f64> },
    Cylinder { radius: f64, length: f64 },
    Capsule { radius: f64, length: f64 },
    Sphere { radius: f64 },
    /// A mesh the description points at but does not contain. `scale` defaults to `(1, 1, 1)` when
    /// the attribute is absent, which is URDF's own default.
    Mesh { uri: String, scale: Vector3<f64> },
}

/// One shape, with the link it belongs to and its pose in that link's frame.
#[derive(Clone, Debug)]
pub struct GeometryRef {
    pub link: String,
    pub role: GeomRole,
    pub origin: Iso,
    pub geometry: LinkGeometry,
}

fn pose(p: &urdf_rs::Pose) -> Iso {
    let t = Translation3::new(p.xyz[0], p.xyz[1], p.xyz[2]);
    let r = UnitQuaternion::from_euler_angles(p.rpy[0], p.rpy[1], p.rpy[2]);
    Iso::from_parts(t, r)
}

fn geom(g: &urdf_rs::Geometry) -> LinkGeometry {
    match g {
        urdf_rs::Geometry::Box { size } => LinkGeometry::Box { size: Vector3::new(size[0], size[1], size[2]) },
        urdf_rs::Geometry::Cylinder { radius, length } => LinkGeometry::Cylinder { radius: *radius, length: *length },
        urdf_rs::Geometry::Capsule { radius, length } => LinkGeometry::Capsule { radius: *radius, length: *length },
        urdf_rs::Geometry::Sphere { radius } => LinkGeometry::Sphere { radius: *radius },
        urdf_rs::Geometry::Mesh { filename, scale } => LinkGeometry::Mesh {
            uri: filename.clone(),
            // URDF's default scale is unity, and an absent attribute means unity rather than zero
            scale: scale.map(|s| Vector3::new(s[0], s[1], s[2])).unwrap_or_else(|| Vector3::new(1.0, 1.0, 1.0)),
        },
    }
}

/// **Every shape a URDF declares**, in document order, visual and collision alike.
///
/// Parses from a string, like every other loader in this crate. `Err` only if the XML does not parse
/// as a URDF at all — a description with no geometry is an empty list, which is a different fact and
/// the caller should be able to tell them apart.
pub fn geometry_from_urdf(xml: &str) -> Result<Vec<GeometryRef>, String> {
    let robot = urdf_rs::read_from_string(xml).map_err(|e| format!("URDF parse error: {e}"))?;
    let mut out = Vec::new();
    for link in &robot.links {
        for v in &link.visual {
            out.push(GeometryRef { link: link.name.clone(), role: GeomRole::Visual, origin: pose(&v.origin), geometry: geom(&v.geometry) });
        }
        for c in &link.collision {
            out.push(GeometryRef { link: link.name.clone(), role: GeomRole::Collision, origin: pose(&c.origin), geometry: geom(&c.geometry) });
        }
    }
    Ok(out)
}

/// **Expand a mesh URI against a package→root table**, as pure string work.
///
/// Handles the three forms a description actually uses: `package://pkg/rest/of/path` (ROS's
/// convention, resolved through the table), `file:///absolute/path` and `file://relative`, and a bare
/// relative path, which is returned unchanged because only the caller knows what it is relative to.
///
/// `None` when a `package://` URI names a package the table does not carry, which is the case worth
/// reporting: it is a missing dependency, not a missing file, and the caller can say so.
///
/// This does not touch the filesystem and does not normalise `..` — it is the mapping step, and the
/// caller owns the fetch. That is deliberate: it is what lets the same code path work in a browser
/// against an HTTP fetch or a bundled asset map.
pub fn resolve_uri(uri: &str, package_roots: &[(&str, &str)]) -> Option<String> {
    if let Some(rest) = uri.strip_prefix("package://") {
        let (pkg, tail) = rest.split_once('/')?;
        let root = package_roots.iter().find(|(name, _)| *name == pkg).map(|(_, r)| *r)?;
        let sep = if root.ends_with('/') || root.is_empty() { "" } else { "/" };
        return Some(format!("{root}{sep}{tail}"));
    }
    if let Some(rest) = uri.strip_prefix("file://") {
        return Some(rest.to_string());
    }
    // `model://` is Gazebo's spelling of the same idea; treat it identically so an SDF-derived URI
    // resolves rather than silently falling through to "relative path".
    if let Some(rest) = uri.strip_prefix("model://") {
        let (pkg, tail) = rest.split_once('/')?;
        let root = package_roots.iter().find(|(name, _)| *name == pkg).map(|(_, r)| *r)?;
        let sep = if root.ends_with('/') || root.is_empty() { "" } else { "/" };
        return Some(format!("{root}{sep}{tail}"));
    }
    (!uri.is_empty()).then(|| uri.to_string())
}

/// **Generate the mesh of a primitive shape**, so a description made of primitives needs no asset.
///
/// `segments` is the circumferential resolution for the curved shapes and is ignored for a box. A
/// tessellated shape is **inscribed**, so its volume is an under-estimate that converges at second
/// order in `segments`; the tests measure that rate rather than trusting one value.
///
/// `None` for [`LinkGeometry::Mesh`], which by definition is not generated, and for a non-finite or
/// non-positive dimension.
pub fn primitive_mesh(g: &LinkGeometry, segments: usize) -> Option<TriMesh3> {
    let n = segments.max(3);
    let ok = |v: &[f64]| v.iter().all(|x| x.is_finite() && *x > 0.0);
    match g {
        LinkGeometry::Box { size } => {
            if !ok(size.as_slice()) {
                return None;
            }
            let h = size / 2.0;
            let verts: Vec<Vector3<f64>> = [
                (-1.0, -1.0, -1.0), (1.0, -1.0, -1.0), (1.0, 1.0, -1.0), (-1.0, 1.0, -1.0),
                (-1.0, -1.0, 1.0), (1.0, -1.0, 1.0), (1.0, 1.0, 1.0), (-1.0, 1.0, 1.0),
            ]
            .iter()
            .map(|(x, y, z)| Vector3::new(x * h.x, y * h.y, z * h.z))
            .collect();
            // outward-wound, which is what makes the volume positive
            let tris = vec![
                [0, 2, 1], [0, 3, 2], // −z
                [4, 5, 6], [4, 6, 7], // +z
                [0, 1, 5], [0, 5, 4], // −y
                [1, 2, 6], [1, 6, 5], // +x
                [2, 3, 7], [2, 7, 6], // +y
                [3, 0, 4], [3, 4, 7], // −x
            ];
            Some(TriMesh3 { verts, tris })
        }
        LinkGeometry::Sphere { radius } => {
            if !ok(&[*radius]) {
                return None;
            }
            Some(lat_long(*radius, *radius, n, 0.0))
        }
        LinkGeometry::Cylinder { radius, length } => {
            if !ok(&[*radius, *length]) {
                return None;
            }
            Some(tube(*radius, *length, n))
        }
        LinkGeometry::Capsule { radius, length } => {
            if !ok(&[*radius, *length]) {
                return None;
            }
            // a cylinder of `length` capped by two hemispheres of `radius`, which is URDF's capsule
            Some(lat_long(*radius, *radius, n, *length))
        }
        LinkGeometry::Mesh { .. } => None,
    }
}

/// A latitude-longitude surface of revolution about z: a sphere when `gap` is zero, a capsule when it
/// is the cylindrical length. `n` bands of latitude per hemisphere, `2n` around.
fn lat_long(r: f64, _r2: f64, n: usize, gap: f64) -> TriMesh3 {
    use core::f64::consts::PI;
    let half = gap / 2.0;
    let mut verts = vec![Vector3::new(0.0, 0.0, r + half)];
    // northern hemisphere down to the equator, then the southern one, offset by ±gap/2
    let rings = 2 * n;
    for i in 1..rings {
        let theta = PI * i as f64 / rings as f64;
        let (st, ct) = (theta.sin(), theta.cos());
        let z = r * ct + if ct >= 0.0 { half } else { -half };
        for j in 0..2 * n {
            let phi = 2.0 * PI * j as f64 / (2 * n) as f64;
            verts.push(Vector3::new(r * st * phi.cos(), r * st * phi.sin(), z));
        }
    }
    verts.push(Vector3::new(0.0, 0.0, -r - half));
    let ring = |i: usize, j: usize| 1 + (i - 1) * 2 * n + j % (2 * n);
    let south = verts.len() - 1;
    let mut tris = Vec::new();
    for j in 0..2 * n {
        tris.push([0, ring(1, j), ring(1, j + 1)]);
    }
    for i in 1..rings - 1 {
        for j in 0..2 * n {
            tris.push([ring(i, j), ring(i + 1, j), ring(i + 1, j + 1)]);
            tris.push([ring(i, j), ring(i + 1, j + 1), ring(i, j + 1)]);
        }
    }
    for j in 0..2 * n {
        tris.push([south, ring(rings - 1, j + 1), ring(rings - 1, j)]);
    }
    TriMesh3 { verts, tris }
}

/// A closed right circular cylinder along z, centred, with `n` sides and two flat caps.
fn tube(r: f64, length: f64, n: usize) -> TriMesh3 {
    use core::f64::consts::PI;
    let h = length / 2.0;
    let mut verts = Vec::with_capacity(2 * n + 2);
    for j in 0..n {
        let phi = 2.0 * PI * j as f64 / n as f64;
        verts.push(Vector3::new(r * phi.cos(), r * phi.sin(), h));
    }
    for j in 0..n {
        let phi = 2.0 * PI * j as f64 / n as f64;
        verts.push(Vector3::new(r * phi.cos(), r * phi.sin(), -h));
    }
    let top_c = verts.len();
    verts.push(Vector3::new(0.0, 0.0, h));
    let bot_c = verts.len();
    verts.push(Vector3::new(0.0, 0.0, -h));

    let mut tris = Vec::new();
    for j in 0..n {
        let (a, b) = (j, (j + 1) % n);
        // side, outward
        tris.push([a, a + n, b + n]);
        tris.push([a, b + n, b]);
        // caps
        tris.push([top_c, a, b]);
        tris.push([bot_c, b + n, a + n]);
    }
    TriMesh3 { verts, tris }
}

/// Move every vertex of a mesh by a rigid transform, for placing a shape at its `<origin>`.
pub fn transform_mesh(mesh: &TriMesh3, tf: &Iso) -> TriMesh3 {
    TriMesh3 {
        verts: mesh.verts.iter().map(|v| (tf * Point3::from(*v)).coords).collect(),
        tris: mesh.tris.clone(),
    }
}

/// **Compose several shapes in one link frame into one [`LinkInertia`].**
///
/// Each part is placed at its origin, integrated at the shared `density`, and then composed by
/// parallel-axis about the **combined** centre of mass. `None` if any part fails to integrate — a
/// part with a non-positive volume means an inward-wound or open mesh, and a body assembled from one
/// of those simulates and is wrong.
///
/// ⛔ This is not an average of the parts' tensors, and the two differ by a factor you would not
/// notice. See the module note.
pub fn inertia_of_parts(parts: &[(TriMesh3, Iso)], density: f64) -> Option<LinkInertia> {
    if parts.is_empty() {
        return None;
    }
    let mut acc: Option<LinkInertia> = None;
    for (mesh, tf) in parts {
        // Integrate in the mesh's own frame, then transform: `solid_inertia` returns the tensor about
        // the part's COM, and `transform_inertia` rotates it and moves the COM, which is exactly the
        // pair `combine_inertia` then expects.
        let li = transform_inertia(&solid_inertia(mesh, density)?, tf);
        acc = Some(match acc {
            None => li,
            Some(a) => combine_inertia(&a, &li),
        });
    }
    acc
}

/// **The inertia a URDF's own geometry implies for one link**, for the primitive shapes, needing no
/// asset at all.
///
/// Prefers `<collision>` shapes and falls back to `<visual>` when a link declares only visual
/// geometry. Mesh references are **skipped** — they need bytes this function does not fetch — and the
/// count of skipped meshes is returned so a caller can tell "this link is fully described by
/// primitives" from "this link needs three mesh files I have not supplied". That distinction is the
/// whole reason this returns a tuple.
pub fn primitive_link_inertia(
    geometry: &[GeometryRef],
    link: &str,
    density: f64,
    segments: usize,
) -> (Option<LinkInertia>, usize) {
    let of_role = |role: GeomRole| -> Vec<&GeometryRef> {
        geometry.iter().filter(|g| g.link == link && g.role == role).collect()
    };
    let chosen = {
        let c = of_role(GeomRole::Collision);
        if c.is_empty() {
            of_role(GeomRole::Visual)
        } else {
            c
        }
    };
    let mut parts = Vec::new();
    let mut skipped = 0usize;
    for g in chosen {
        match primitive_mesh(&g.geometry, segments) {
            Some(m) => parts.push((m, g.origin)),
            None => skipped += 1,
        }
    }
    (inertia_of_parts(&parts, density), skipped)
}

#[cfg(test)]
mod tests {
    use super::*;
    use core::f64::consts::PI;

    const DENSITY: f64 = 2700.0;

    /// A box mesh is EXACT, so its volume and inertia must hit the closed form to round-off — no
    /// convergence argument, no tolerance to justify.
    #[test]
    fn a_generated_box_is_exact_against_its_closed_form() {
        let (a, b, c) = (0.4f64, 0.12f64, 0.06f64);
        let m = primitive_mesh(&LinkGeometry::Box { size: Vector3::new(a, b, c) }, 8).expect("a box generates");
        assert!((m.volume() - a * b * c).abs() < 1e-18, "volume {} vs {}", m.volume(), a * b * c);
        assert!(m.centroid().norm() < 1e-18, "URDF's box is centred on its frame, got {:?}", m.centroid());

        let li = solid_inertia(&m, DENSITY).expect("well-posed");
        let mass = DENSITY * a * b * c;
        assert!((li.mass - mass).abs() < 1e-12, "mass {} vs {mass}", li.mass);
        for (i, want) in [
            (0, mass * (b * b + c * c) / 12.0),
            (1, mass * (a * a + c * c) / 12.0),
            (2, mass * (a * a + b * b) / 12.0),
        ] {
            assert!((li.inertia[(i, i)] - want).abs() < 1e-12, "I[{i}{i}] = {} vs {want}", li.inertia[(i, i)]);
        }
        eprintln!("  {a}×{b}×{c} box: m {:.4} kg, I = diag({:.6}, {:.6}, {:.6})", li.mass, li.inertia[(0, 0)], li.inertia[(1, 1)], li.inertia[(2, 2)]);
    }

    /// The curved primitives converge to their analytic solids at the second-order rate an inscribed
    /// tessellation must show. Checking the RATE is what separates a correct facet layout from one
    /// that is systematically wrong — the value alone can be matched by a wrong winding.
    #[test]
    fn the_curved_primitives_converge_to_their_closed_forms_at_second_order() {
        let (r, l) = (0.09f64, 0.3f64);
        let cases: [(&str, LinkGeometry, f64); 3] = [
            ("sphere", LinkGeometry::Sphere { radius: r }, 4.0 / 3.0 * PI * r.powi(3)),
            ("cylinder", LinkGeometry::Cylinder { radius: r, length: l }, PI * r * r * l),
            ("capsule", LinkGeometry::Capsule { radius: r, length: l }, PI * r * r * l + 4.0 / 3.0 * PI * r.powi(3)),
        ];
        for (name, g, want) in cases {
            let e = |n: usize| (primitive_mesh(&g, n).expect("generates").volume() / want - 1.0).abs();
            let (e8, e16, e32) = (e(8), e(16), e(32));
            eprintln!("  {name:9} V -> {want:.8}: error {e8:.3e} -> {e16:.3e} -> {e32:.3e} (ratios {:.2}, {:.2})", e8 / e16, e16 / e32);
            assert!(e32 < e16 && e16 < e8, "{name}: refinement must reduce the error");
            for (x, y) in [(e8, e16), (e16, e32)] {
                assert!((3.0..5.5).contains(&(x / y)), "{name}: error must fall ~4x per refinement, got {:.2}x", x / y);
            }
            // ⛔ My first version asserted `e32 < 5e-3` for all three, and the cylinder fails it at
            // 6.413e-3 — not because the mesh is wrong but because an inscribed n-gon prism at n=32
            // really is that far from the circle. An arbitrary tolerance was the wrong instrument.
            assert!(e32 < 2e-2, "{name}: and be close by the finest level, got {e32:.3e}");
        }

        // THE EXACT ORACLE for the cylinder, which needs no tolerance at all: an inscribed n-gon
        // prism has volume (n/2)·r²·sin(2π/n)·L exactly, so the relative deficit is
        // 1 − (n/2π)·sin(2π/n) — a closed form the measured error must MATCH, not merely stay under.
        for n in [8usize, 16, 32, 64, 256] {
            let m = primitive_mesh(&LinkGeometry::Cylinder { radius: r, length: l }, n).expect("generates");
            let exact_prism = (n as f64 / 2.0) * r * r * (2.0 * PI / n as f64).sin() * l;
            let predicted_deficit = 1.0 - (n as f64 / (2.0 * PI)) * (2.0 * PI / n as f64).sin();
            let measured_deficit = 1.0 - m.volume() / (PI * r * r * l);
            assert!(
                (m.volume() / exact_prism - 1.0).abs() < 1e-14,
                "n={n}: the mesh must BE the inscribed prism, {} vs {exact_prism}", m.volume()
            );
            assert!(
                (measured_deficit - predicted_deficit).abs() < 1e-12,
                "n={n}: deficit {measured_deficit:.9e} must equal the closed form {predicted_deficit:.9e}"
            );
        }
        eprintln!("  cylinder: the measured volume deficit equals 1 − (n/2π)sin(2π/n) to 1e-12 at n = 8, 16, 32, 64, 256");

        // and the cylinder's inertia has DIFFERENT axial and radial terms, so this also checks the
        // axis convention: URDF's cylinder is along z, and I_zz = ½mr² while I_xx = m(3r²+l²)/12
        let m = primitive_mesh(&LinkGeometry::Cylinder { radius: r, length: l }, 256).expect("generates");
        let li = solid_inertia(&m, DENSITY).expect("well-posed");
        let mass = DENSITY * PI * r * r * l;
        let (want_zz, want_xx) = (0.5 * mass * r * r, mass * (3.0 * r * r + l * l) / 12.0);
        eprintln!("  cylinder n=256: I_zz {:.6} vs {want_zz:.6}, I_xx {:.6} vs {want_xx:.6}", li.inertia[(2, 2)], li.inertia[(0, 0)]);
        assert!((li.inertia[(2, 2)] / want_zz - 1.0).abs() < 1e-3, "I_zz off: {} vs {want_zz}", li.inertia[(2, 2)]);
        assert!((li.inertia[(0, 0)] / want_xx - 1.0).abs() < 1e-3, "I_xx off: {} vs {want_xx}", li.inertia[(0, 0)]);
        assert!(
            (li.inertia[(2, 2)] - li.inertia[(0, 0)]).abs() / want_xx > 0.1,
            "the axial and radial terms must actually differ, or this test cannot see a wrong axis"
        );
    }

    /// **THE COMPOSITION ORACLE, and the reason `inertia_of_parts` exists.** Two unit cubes side by
    /// side ARE a 2×1×1 box, so composing them must give that box's analytic inertia. Averaging the
    /// two cubes' own tensors instead gives `m/6` where the truth is `5m/12` — 2.5× too small, and
    /// entirely plausible-looking.
    #[test]
    fn two_cubes_compose_into_the_box_they_form() {
        let cube = primitive_mesh(&LinkGeometry::Box { size: Vector3::new(1.0, 1.0, 1.0) }, 4).expect("generates");
        let left = Iso::from_parts(Translation3::new(-0.5, 0.0, 0.0), UnitQuaternion::identity());
        let right = Iso::from_parts(Translation3::new(0.5, 0.0, 0.0), UnitQuaternion::identity());
        let got = inertia_of_parts(&[(cube.clone(), left), (cube.clone(), right)], DENSITY).expect("well-posed");

        let whole = primitive_mesh(&LinkGeometry::Box { size: Vector3::new(2.0, 1.0, 1.0) }, 4).expect("generates");
        let want = solid_inertia(&whole, DENSITY).expect("well-posed");

        assert!((got.mass - want.mass).abs() < 1e-9, "mass {} vs {}", got.mass, want.mass);
        assert!(got.com.norm() < 1e-12, "the compound COM is the origin, got {:?}", got.com);
        assert!((got.inertia - want.inertia).amax() < 1e-9, "compound inertia differs by {}", (got.inertia - want.inertia).amax());

        // the closed form, independently: a 2×1×1 box, I_yy = m(a²+c²)/12 = 5m/12
        let mass = DENSITY * 2.0;
        let want_yy = mass * (4.0 + 1.0) / 12.0;
        assert!((got.inertia[(1, 1)] - want_yy).abs() < 1e-9, "I_yy {} vs the closed form {want_yy}", got.inertia[(1, 1)]);

        // and the WRONG composition, computed here so the factor is on record rather than asserted
        let one = solid_inertia(&cube, DENSITY).expect("well-posed");
        let averaged = one.inertia[(1, 1)] * 2.0; // "add the tensors", the natural mistake
        eprintln!("  two cubes: I_yy correct {:.4}, adding the tensors gives {:.4} ({:.2}x too small)", got.inertia[(1, 1)], averaged, got.inertia[(1, 1)] / averaged);
        assert!(
            (got.inertia[(1, 1)] / averaged - 2.5).abs() < 1e-6,
            "the naive composition must be exactly 2.5x too small here, or this fixture no longer demonstrates the trap"
        );
    }

    const ARM_URDF: &str = r#"<robot name="geo">
      <link name="base">
        <collision><origin xyz="0 0 0.05" rpy="0 0 0"/><geometry><box size="0.2 0.2 0.1"/></geometry></collision>
      </link>
      <link name="l1">
        <visual><geometry><mesh filename="package://geo_description/meshes/l1.stl" scale="0.001 0.001 0.001"/></geometry></visual>
        <collision><origin xyz="0.15 0 0" rpy="0 1.5708 0"/><geometry><cylinder radius="0.03" length="0.3"/></geometry></collision>
      </link>
      <link name="l2">
        <visual><geometry><mesh filename="l2.obj"/></geometry></visual>
      </link>
      <link name="tip"/>
      <joint name="j1" type="revolute"><parent link="base"/><child link="l1"/>
        <origin xyz="0 0 0.1" rpy="0 0 0"/><axis xyz="0 0 1"/>
        <limit lower="-3" upper="3" effort="10" velocity="3"/></joint>
      <joint name="j2" type="revolute"><parent link="l1"/><child link="l2"/>
        <origin xyz="0.3 0 0" rpy="0 0 0"/><axis xyz="0 1 0"/>
        <limit lower="-3" upper="3" effort="10" velocity="3"/></joint>
      <joint name="jt" type="fixed"><parent link="l2"/><child link="tip"/><origin xyz="0.1 0 0" rpy="0 0 0"/></joint>
    </robot>"#;

    /// The geometry `urdf_rs` was already parsing and this crate discarded, now reachable — with the
    /// scale, the role, and the origin each checked, because each has a default that is easy to get
    /// wrong (scale defaults to unity, not zero).
    #[test]
    fn the_geometry_urdf_rs_already_parsed_is_now_reachable() {
        let geo = geometry_from_urdf(ARM_URDF).expect("the fixture parses");
        // base: 1 collision. l1: 1 visual + 1 collision. l2: 1 visual. tip: nothing. Four in all —
        // I first wrote 5 here from counting the fixture by eye rather than by reading it.
        assert_eq!(geo.len(), 4, "expected 4 shapes, got {:?}", geo.iter().map(|g| (&g.link, g.role)).collect::<Vec<_>>());

        let base: Vec<_> = geo.iter().filter(|g| g.link == "base").collect();
        assert_eq!(base.len(), 1);
        assert_eq!(base[0].role, GeomRole::Collision);
        assert_eq!(base[0].geometry, LinkGeometry::Box { size: Vector3::new(0.2, 0.2, 0.1) });
        assert!((base[0].origin.translation.vector - Vector3::new(0.0, 0.0, 0.05)).norm() < 1e-15, "the origin must be carried");

        let scaled = geo.iter().find(|g| matches!(&g.geometry, LinkGeometry::Mesh { uri, .. } if uri.ends_with("l1.stl"))).expect("l1's mesh");
        match &scaled.geometry {
            LinkGeometry::Mesh { uri, scale } => {
                assert_eq!(uri, "package://geo_description/meshes/l1.stl");
                assert!((scale - Vector3::new(0.001, 0.001, 0.001)).norm() < 1e-18, "the mm scale must be carried, got {scale:?}");
            }
            other => panic!("expected a mesh, got {other:?}"),
        }
        // ⛔ an ABSENT scale attribute is UNITY, not zero. A zero default would silently collapse the
        // mesh to a point and yield a zero inertia, which is the kind of default that looks like data.
        let unscaled = geo.iter().find(|g| matches!(&g.geometry, LinkGeometry::Mesh { uri, .. } if uri == "l2.obj")).expect("l2's mesh");
        match &unscaled.geometry {
            LinkGeometry::Mesh { scale, .. } => assert_eq!(*scale, Vector3::new(1.0, 1.0, 1.0), "an absent scale is unity"),
            other => panic!("expected a mesh, got {other:?}"),
        }

        // the rotated cylinder carries its rpy
        // The rotated cylinder carries its rpy — checked by what the rotation DOES, not by reading
        // Euler angles back out of it.
        //
        // ⛔ My first version asserted `(pitch - 1.5708).abs() < 1e-6` and measured 1.5707926535755432,
        // off by 7.3e-6. That is not a carrying error: `rpy="0 1.5708 0"` sits 3.7e-6 from π/2, which is
        // a GIMBAL SINGULARITY of the Z-Y-X decomposition, and pitch readback is ill-conditioned there.
        // A pitch of +π/2 about y maps ẑ to x̂, which is a well-conditioned statement about the same
        // rotation, so that is what this asserts.
        let cyl = geo.iter().find(|g| matches!(g.geometry, LinkGeometry::Cylinder { .. })).expect("l1's collision");
        let mapped = cyl.origin.rotation * Vector3::z();
        assert!(
            (mapped - Vector3::x()).norm() < 1e-5,
            "a pitch of +pi/2 about y must send the cylinder's own z axis to x, got {mapped:?}"
        );
        assert!(cyl.origin.translation.vector.x > 0.14, "and its offset, got {:?}", cyl.origin.translation.vector);
        eprintln!("  URDF geometry: {} shapes, {} collision, {} mesh references", geo.len(),
            geo.iter().filter(|g| g.role == GeomRole::Collision).count(),
            geo.iter().filter(|g| matches!(g.geometry, LinkGeometry::Mesh { .. })).count());
    }

    /// A description made of primitives becomes a simulable body from the XML alone, and the skipped
    /// count is what tells a caller which links still need assets.
    #[test]
    fn a_primitive_description_yields_a_body_with_no_asset_at_all() {
        let geo = geometry_from_urdf(ARM_URDF).expect("parses");

        // `base` is one box: fully described, nothing skipped
        let (li, skipped) = primitive_link_inertia(&geo, "base", DENSITY, 64);
        let li = li.expect("a box link has an inertia");
        assert_eq!(skipped, 0, "base needs no asset");
        let mass = DENSITY * 0.2 * 0.2 * 0.1;
        assert!((li.mass - mass).abs() < 1e-9, "mass {} vs {mass}", li.mass);
        assert!((li.com - Vector3::new(0.0, 0.0, 0.05)).norm() < 1e-12, "the COM sits at the shape's origin, got {:?}", li.com);

        // `l1` declares a mesh (visual) AND a cylinder (collision): collision wins, so nothing is
        // skipped and no asset is needed
        let (li1, skipped1) = primitive_link_inertia(&geo, "l1", DENSITY, 128);
        let li1 = li1.expect("the collision cylinder describes l1");
        assert_eq!(skipped1, 0, "the collision geometry is primitive, so no mesh is needed");
        let want = DENSITY * PI * 0.03 * 0.03 * 0.3;
        assert!((li1.mass / want - 1.0).abs() < 1e-3, "cylinder mass {} vs {want}", li1.mass);

        // `l2` declares ONLY a visual mesh: no inertia is available and the caller is told why
        let (li2, skipped2) = primitive_link_inertia(&geo, "l2", DENSITY, 64);
        assert!(li2.is_none(), "a mesh-only link cannot be integrated without its asset");
        assert_eq!(skipped2, 1, "and the caller must be told one mesh was skipped, not just handed None");

        // `tip` declares nothing at all, which is a different fact again
        let (li3, skipped3) = primitive_link_inertia(&geo, "tip", DENSITY, 64);
        assert!(li3.is_none() && skipped3 == 0, "no geometry is not the same as unresolved geometry");
        eprintln!("  base {:.4} kg (0 skipped), l1 {:.4} kg (0 skipped), l2 none (1 skipped), tip none (0 skipped)", li.mass, li1.mass);
    }

    /// URI expansion, including the cases that should REFUSE. A `package://` URI naming a package the
    /// caller did not supply is a missing dependency, and reporting it as a relative path would send
    /// the caller looking for a file called `package:`.
    #[test]
    fn uri_resolution_expands_what_it_can_and_refuses_what_it_cannot() {
        let roots = [("geo_description", "/opt/ros/share/geo_description"), ("other", "assets/other/")];
        for (uri, want) in [
            ("package://geo_description/meshes/l1.stl", Some("/opt/ros/share/geo_description/meshes/l1.stl")),
            ("package://other/a/b.obj", Some("assets/other/a/b.obj")), // a trailing slash must not double
            ("model://other/a/b.obj", Some("assets/other/a/b.obj")),   // Gazebo's spelling of the same idea
            ("file:///abs/path/x.stl", Some("/abs/path/x.stl")),
            ("file://rel/x.stl", Some("rel/x.stl")),
            ("meshes/l2.obj", Some("meshes/l2.obj")), // a bare relative path is the caller's business
            ("package://missing_pkg/x.stl", None),    // a package the table does not carry
            ("package://noslash", None),              // malformed: no path after the package
            ("", None),
        ] {
            let got = resolve_uri(uri, &roots);
            assert_eq!(got.as_deref(), want, "resolving {uri:?}");
        }
        assert_eq!(resolve_uri("package://geo_description/x", &[]).as_deref(), None, "an empty table resolves no package");
    }

    /// Refusals, and the one that matters most: a dimension of zero or a non-finite one must not
    /// produce a degenerate mesh that integrates to a zero-mass body.
    #[test]
    fn a_degenerate_primitive_is_refused_rather_than_generated() {
        assert!(primitive_mesh(&LinkGeometry::Box { size: Vector3::new(0.1, 0.1, 0.1) }, 8).is_some(), "control");
        for bad in [
            LinkGeometry::Box { size: Vector3::new(0.1, 0.0, 0.1) },
            LinkGeometry::Box { size: Vector3::new(0.1, -1.0, 0.1) },
            LinkGeometry::Box { size: Vector3::new(f64::NAN, 0.1, 0.1) },
            LinkGeometry::Sphere { radius: 0.0 },
            LinkGeometry::Sphere { radius: f64::INFINITY },
            LinkGeometry::Cylinder { radius: 0.02, length: 0.0 },
            LinkGeometry::Cylinder { radius: 0.0, length: 0.2 },
            LinkGeometry::Capsule { radius: -0.02, length: 0.2 },
        ] {
            assert!(primitive_mesh(&bad, 16).is_none(), "a degenerate dimension must be refused: {bad:?}");
        }
        assert!(
            primitive_mesh(&LinkGeometry::Mesh { uri: "x.stl".into(), scale: Vector3::new(1.0, 1.0, 1.0) }, 16).is_none(),
            "a mesh reference is not a generated primitive"
        );
        // segments below 3 cannot make a solid, so it is clamped rather than producing a sliver
        let coarse = primitive_mesh(&LinkGeometry::Cylinder { radius: 0.1, length: 0.2 }, 0).expect("clamped, not refused");
        assert!(coarse.volume() > 0.0, "the clamp must still yield a positive volume, got {}", coarse.volume());
        assert!(inertia_of_parts(&[], DENSITY).is_none(), "no parts is not a body");
        // ⛔ WHAT `urdf_rs` ACTUALLY REJECTS, measured rather than assumed. I first asserted that
        // `<not-a-urdf/>` is an error; it is not — the parser accepts any well-formed XML element as a
        // robot with no links. It errors only when the input contains no element at all. Asserting the
        // library's real contract is the point; asserting the one I expected would have been a test of
        // my assumption.
        for bad in ["", "hello", r#"<robot name="a"><link name="b">"#, r#"{"a":1}"#] {
            assert!(geometry_from_urdf(bad).is_err(), "input with no XML element must be an error: {bad:?}");
        }
        for empty in ["<not-a-urdf/>", r#"<robot name="e"><link name="a"/></robot>"#] {
            assert!(
                geometry_from_urdf(empty).is_ok_and(|g| g.is_empty()),
                "well-formed XML declaring no geometry is an EMPTY LIST, not an error: {empty:?}"
            );
        }
    }
}
